### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmprt19wbn7'

### ISSUE THREAD

**Issue by InsecureSpike** [bilelmoussaoui/Hardcode-Tray#513]
### Specifications
- Hardcode-Tray version : `4.1-1`
- Distribution : `Manjaro Linux i3 17.1.7 Hakoila`
- Gtk version : ``
- Inkscape version : `0.92.3-1`
- Cairo version : `1.15.10-1`
- Sni-qt version: `r.-1`
- Application name :  ``
- Application version : ``

When I run hardcode-tray with command:
sudo -E hardcode-tray

Welcome to Hardcode-Tray!
Desktop Environment: I3
Scaling Factor: 1
Icon Size: 22
Icon Theme: flatpac-equilux-icons
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..

Chromium            [#####...............................] 1/7 14.3% 0.30s
Hexchat             [##########..........................] 2/7 28.6% 1.13s
HP Printer          [###############.....................] 3/7 42.9% 0.29s
Mailspring          [##########################..........] 5/7 71.4% 0.95s
overGrive           [###############################.....] 6/7 85.7% 0.00s
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 119, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 148, in do_action
    self.install()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/decorators.py", line 58, in wrapper
    func(app)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 96, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 50, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/electron.py", line 38, in install_icon
    png_bytes = get_pngbytes(icon)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/utils.py", line 216, in get_pngbytes
    App.icon_size())
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/svg/svg.py", line 92, in to_bin
    with open(outfile, 'rb') as temppng:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmprt19wbn7'

**Comment by InsecureSpike** [comment]
sorry i misspelled one of the target icons

**Comment by data4pass** [comment]
Hello, could you explain what exactly did you mean by deleting target icon folder? I'm currently having the exact same problem.
