### ISSUE TITLE
line 120 exception

### ISSUE THREAD

**Issue by romanlex** [bilelmoussaoui/Hardcode-Tray#514]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Arch Linux`
- Gtk version : `3.22`
- Inkscape version : `0.92.2`
- Sni-qt version: `last from AUR`

I'm trying apply this and get exception on line 120
```bash
[roman@n550jv .config]$ sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus

(hardcode-tray:31004): Gtk-WARNING **: 11:12:52.638: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(hardcode-tray:31004): Gtk-WARNING **: 11:12:52.638: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(hardcode-tray:31004): Gtk-WARNING **: 11:12:52.638: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Добро пожаловать в Hardcode-Tray!
Рабочее окружение: Kde
Увеличение: 1
Размер значков: 22
Тема значков: Papirus
Средство конвертирования: RSVGConvert
Цель:Всё
1 - Исправить
2 - Восстановить
3 - Очистить резервный кэш
Выберите:1
Исправление...


Bitcoin             [###.................................] 1/11 9.1% 0.00s
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 120, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 151, in do_action
    self.install()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/decorators.py", line 59, in wrapper
    func(app)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 97, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 51, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 66, in install_icon
    self.set_icon(icon, icon_path, png_bytes, True)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 48, in set_icon
    self.set_binary_file(path.join(str(icon_path), self.binary))
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 44, in set_binary_file
    self.pak = DataPack(binary_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 32, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 66, in _read
    raise Exception
Exception
[roman@n550jv .config]$ 
```

**Comment by bilelmoussaoui** [comment]
Shouldn't happen at all. Which version of Chrome/Chromium are you using?

**Comment by romanlex** [comment]
When I'm install version from aur(not git version) all work properly

**Comment by bilelmoussaoui** [comment]
You should never use the git version. It's for experienced users only. Closing
