### ISSUE TITLE
Fresh Git-version not worked

### ISSUE THREAD

**Issue by varlesh** [bilelmoussaoui/Hardcode-Tray#570]
KDE Neon UE (Ubuntu 18.04)
LOG:
```
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 91, in _read
    self._parse_paths(data["app_path"], "app_path")
UnboundLocalError: local variable 'data' referenced before assignment
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/var/crash/_usr_bin_hardcode-tray.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 91, in _read
    self._parse_paths(data["app_path"], "app_path")
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by varlesh** [comment]
I'm have this error if use hardcode-tray for all apps:
```
sudo -E hardcode-tray -ct RSVGConvert -s 22 --theme Papirus-Dark
Добро пожаловать в Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Рабочее окружение: Kde
Увеличение: 1
Размер значков: 22
Тема значков: Papirus-Dark
Средство конвертирования: RSVGConvert
Цель:Всё
1 - Исправить
2 - Восстановить
3 - Очистить резервный кэш
Выберите:1
Исправление...


Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 91, in _read
    self._parse_paths(data["app_path"], "app_path")
UnboundLocalError: local variable 'data' referenced before assignment
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/var/crash/_usr_bin_hardcode-tray.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 91, in _read
    self._parse_paths(data["app_path"], "app_path")
UnboundLocalError: local variable 'data' referenced before assignment
```
but script worked normal if use for only single app:
```
sudo -E hardcode-tray -ct RSVGConvert -s 22 --theme Papirus-Dark -o telegram
Добро пожаловать в Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Рабочее окружение: Kde
Увеличение: 1
Размер значков: 22
Тема значков: Papirus-Dark
Средство конвертирования: RSVGConvert
Цель:Telegram
1 - Исправить
2 - Восстановить
3 - Очистить резервный кэш
Выберите:1
Исправление...


Telegram            [####################################] 1/1 100.0% 0.16s
Потребовалось 0.16с, чтобы завершить операцию

Готово! Благодарим за использование Hardcode-Tray!
```
