### ISSUE TITLE
Doesn't work at all here

### ISSUE THREAD

**Issue by hrqmonteiro** [bilelmoussaoui/Hardcode-Tray#572]
### Specifications
- Hardcode-Tray version : `last version`
- Distribution : `Arch`
- Gtk version : 3``
- Inkscape version : `0.92.4` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `telegram`
- Application version : `1.5.15.1`

Hardcode tray doesn't work in any application, any theme or any way i tried, everytime i got an error like this:
Traceback (most recent call last):
  File "/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/parser.py", line 91, in _read
    self._parse_paths(data["app_path"], "app_path")
UnboundLocalError: local variable 'data' referenced before assignment

And then it just don't change the tray icon i had before.

**Comment by varlesh** [comment]
this fixed, but not merged now:
https://github.com/bilelmoussaoui/Hardcode-Tray/pull/571

**Comment by hrqmonteiro** [comment]
> this fixed, but not merged now:
> #571

Great! That really fixed, working now, thanks a lot.

**Comment by tudorjnu** [comment]
I am getting the same error now.
