### ISSUE TITLE
Unable to run hardcode-Tray in Debian testing

### ISSUE THREAD

**Issue by jEsuSdA** [bilelmoussaoui/Hardcode-Tray#635]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Debian`
- Gtk version : `3.24`
- Inkscape version : `1.0`
- Cairo version : `1.16.0-4` if installed
- Sni-qt version: `0.2.7+20161212` if installed

### Steps to reproduce the problem

```
# → hardcode-tray 
Unable to init server: Could not connect: Connection refused
Unable to init server: No se pudo conectar: Connection refused
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 103, in <module>
    if not isinstance(App.theme(), dict):
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 177, in theme
    theme = App.get("theme")
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 77, in get
    value = method()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/config/system.py", line 67, in theme
    theme_name = Gtk.Settings.get_default().get_property("gtk-icon-theme-name")
AttributeError: 'NoneType' object has no attribute 'get_property'
```

**Comment by BlueManCZ** [comment]
Do you have installed [pygobject](https://packages.debian.org/source/stable/pygobject)?

**Comment by Anomalocaridid** [comment]
I'm also having this issue. My Linux distro is the EndeavourOS Sway edition and I have the python-gobject package installed.

**Comment by BlueManCZ** [comment]
I noticed this problem on a clean Gentoo installation recently. It was caused by missing gtk libraries. I solved it by installing [`gtk+`](https://packages.gentoo.org/packages/x11-libs/gtk+) package. Check if you have something similar in your distribution.

**Comment by Anomalocaridid** [comment]
@BlueManCZ Thank you, but I'm having a hard time figuring out which library I need to install, especially since I already have gtk2, gtk3, and gtk4 installed.

**Comment by BlueManCZ** [comment]
What desktop environment or window manager do you use? How did you set your current icon theme?

**Comment by Anomalocaridid** [comment]
I use Sway. I set my icon theme using LXAppearance, which set it in ~/.gtkrc-2.0 and ~/.config/gtk-3.0, the latter of which also gets read by [this script](https://github.com/Anomalocaridid/dotfiles/blob/main/.config/sway/scripts/import-gsettings) that gets run every time my Sway config is loaded and uses the gsettings command to set my icon theme, along with a few related settings.

**Comment by BlueManCZ** [comment]
Are you running the script with `sudo -E` as mentioned [here](https://github.com/bilelmoussaoui/Hardcode-Tray/issues/603)? If you run it as a root, problem is, you usually have all the gsettings applied to the user.

**Comment by Anomalocaridid** [comment]
I was unaware that I had to run it as with `sudo -E`. Now it works. Thanks for your help!
