### ISSUE TITLE
Remember the milk

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#703]
Can you fix it?
![image](https://user-images.githubusercontent.com/12108031/130343567-6651e127-fb70-4138-b970-4bcb064d8cc9.png)

**Comment by varlesh** [comment]
It's very strange... script not show errors and apply icons
```
Bauh                [#######.............................] 1/5 20.0% 0.00s
Google Chrome       [##############......................] 2/5 40.0% 0.07s
Mailspring          [######################..............] 3/5 60.0% 2.14s
Remember The Milk   [#############################.......] 4/5 80.0% 0.03s
Steam               [####################################] 5/5 100.0% 0.01s
Потребовалось 2.25с, чтобы завершить операцию

Готово! Благодарим за использование Hardcode-Tray!
```
And on debug all fine!

```
[DEBUG] 2021-08-24 09:23:40 Create new backup folder for Remember The Milk
[DEBUG] 2021-08-24 09:23:40 Creating directory: /home/alex/.config/Hardcode-Tray/Remember The Milk/2021-08-24 09:23:40/
[DEBUG] 2021-08-24 09:23:40 Executing command: rsvg-convert -f png -o /tmp/tmpbn9nztoy -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/rememberthemilk-tray.svg
[DEBUG] 2021-08-24 09:23:40 Executing command: rsvg-convert -f png -o /tmp/tmpz71w9b4x -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/rememberthemilk-unseen-notification.svg
[DEBUG] 2021-08-24 09:23:40 Executing command: rsvg-convert -f png -o /tmp/tmp8u5b1z0v -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/rememberthemilk-notification.svg
```

But icons not replaced!!!
I'm run hardcode-tray, then unpack with asar app.asar and icons not fixed....
And i'm not understand why.
Also i'm verified MD5SUM's befora and after script - they identical:
`89c5aa4024335c2da67a3eccb5c64243  app.asar`

Amy help wanted

**Comment by varlesh** [comment]
also backaup icons not created. Folder config empty:
`/.config/Hardcode-Tray/Remember The Milk/2021-08-24 09:23:40/`

**Comment by varlesh** [comment]
```
{
    "name": "Remember The Milk",
    "app_path": [
        "/opt/RememberTheMilk/",
        "/opt/rememberthemilk/"
    ],
    "icons_path": [
        "/opt/RememberTheMilk/resources/",
        "/opt/rememberthemilk/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray": {
            "original": "resources/balloon-moo.png",
            "theme": "rememberthemilk-tray"
        },
        "tray-unseen": {
            "original": "resources/moo-unseen-notification.png",
            "theme": "rememberthemilk-unseen-notification"
        },
        "tray-notification": {
            "original": "resources/moo-notification.png",
            "theme": "rememberthemilk-notification"
        }
    }
}
```
![Screenshot_20210824_094134](https://user-images.githubusercontent.com/8083855/130562314-4ccf1e55-b29d-46e0-8037-a529064cc1d8.png)

**Comment by varlesh** [comment]
@rauldipeas It's not worked for you too?

**Comment by rauldipeas** [comment]
Updating here, i'm on a very slow connection today...
![image](https://user-images.githubusercontent.com/12108031/130563044-b47eb8b4-272b-4591-a548-bf4b51498a0e.png)

**Comment by varlesh** [comment]
also if move app.asar to another directory (without app.asar.unpacked/resources/MaterialIcons-Regular.woff2), we have error:
```
asar e app.asar unpack
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/alex/GitHub/tmp/RememberTheMilk/app.asar.unpacked/resources/MaterialIcons-Regular.woff2'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.module.exports.readFileSync (/usr/lib/node_modules/asar/lib/disk.js:110:17)
    at Object.module.exports.extractAll (/usr/lib/node_modules/asar/lib/asar.js:200:28)
    at Command.<anonymous> (/usr/lib/node_modules/asar/bin/asar.js:72:10)
    at Command.listener [as _actionHandler] (/usr/lib/node_modules/asar/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/usr/lib/node_modules/asar/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/usr/lib/node_modules/asar/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/usr/lib/node_modules/asar/node_modules/commander/index.js:882:12)
    at Command.parse (/usr/lib/node_modules/asar/node_modules/commander/index.js:717:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/alex/GitHub/tmp/RememberTheMilk/app.asar.unpacked/resources/MaterialIcons-Regular.woff2'
}
```

**Comment by rauldipeas** [comment]
> @rauldipeas It's not worked for you too?

Same result here, no erros and no icon change.

**Comment by varlesh** [comment]
omg, i'm dumb

**Comment by varlesh** [comment]
icons not in asar )))

**Comment by varlesh** [comment]
and normal tray icon it's not `balloon-moo`, but `moo`
LOL

**Comment by rauldipeas** [comment]
> icons not in asar )))

I was thinking about talking to you, but i suposed that you knowed.

**Comment by varlesh** [comment]
fixed

**Comment by varlesh** [comment]
> I was thinking about talking to you, but i suposed that you knowed. :D

Yes, first i'm replace unpacked files. But i'm not seen `moo` icon first and replace `balloon-moo`. After restart app, i'm not seen changes (still would) and i'm spoiled...
But, anyway why icons not replaced on asar? I'm not understand that. Mysteryю...
