### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'which'

### ISSUE THREAD

**Issue by Dhamma-valence** [bilelmoussaoui/Hardcode-Tray#718]
### Specifications
- Hardcode-Tray version : `commit 3797267e600971324ef8b7f1234196a8e9224515`
- Distribution : `Debian Sid/Bookworm`
- Gtk version : `libgtk-3-0:amd64  3.24.30-3`
                        `libgtk-3-0:i386   3.24.24-3`

### Expected behavior and actual behavior

Output of 

`git clone https://github.com/bil-elmoussaoui/Hardcode-Tray;`
`cd Hardcode-Tray;`
`meson builddir --prefix=/usr;`
`sudo ninja -C builddir install;`
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus`

```
Cloning into 'Hardcode-Tray'...
remote: Enumerating objects: 7061, done.
remote: Counting objects: 100% (410/410), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 7061 (delta 282), reused 225 (delta 122), pack-reused 6651
Receiving objects: 100% (7061/7061), 7.81 MiB | 5.16 MiB/s, done.
Resolving deltas: 100% (5023/5023), done.
error: Found argument 'rvm_verbose_flag:0' which wasn't expected, or isn't valid in this context

USAGE:
    true

For more information try --help
.editorconfig  .pylintrc    hardcode-tray.py.in   LICENSE.GPL-3.0  README.md
.git           circle.yml   HardcodeTray          meson.build      screenshots
.github        const.py.in  license               NOTICE           tests
.gitignore     data         LICENSE.BSD-3-Clause  po
The Meson build system
Version: 0.57.1
Source dir: /home/$USER/src/Hardcode-Tray
Build dir: /home/$USER/src/Hardcode-Tray/builddir
Build type: native build
Project name: hardcode-tray
Project version: 4.3
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gobject-introspection-1.0 found: YES 1.70.0
Run-time dependency gtk+-3.0 found: YES 3.24.30
Configuring const.py using configuration
Configuring hardcode-tray using configuration
Build targets in project: 3

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing subdir /home/$USER/src/Hardcode-Tray/data/database to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/utools.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/openbazaar2client.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ao.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/lightcord.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ghetto_skype.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rhythmbox.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/nozbe.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/hamsket.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/yd-tools.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mate-sensors-applet.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mx-updater.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/wicd.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/touchpad-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/xkbmod-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/superproductivity.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/riot.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/yakyak.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rambox-pro.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mintupdate.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/wire.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/premid.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/google-chrome.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/calendar-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/prime-indicator-plus.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/motrix-git.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/popcorntime.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/deltachat.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/guake.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/insync.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/cryptfolder-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rare.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/discord-canary.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/steam.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/dropbox-flatpak.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/my-weather-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/nylas.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/hexchat.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/todoist.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/china-weather.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/trimage.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/bauh.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/sflphone.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mailspring.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/vk.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/hp-printing.qt.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/disper-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/heroic.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/google-tasks-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pcloud-drive.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rambox.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/yamusic.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/harmony.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/yate.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/messengerfordesktop.nwjs.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/teams-for-linux.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/cpod.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pb-for-desktop.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/spotifywebplayer.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/workrave.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/slimbookamdcontroller.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/cisco-anyconnect.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/tutanota-desktop.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pomodoneapp.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rclonetray.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pocket-casts.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rto-proxy.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/variety.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/museeks.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/tweet-tray.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ibus-anthy.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/lyricfier.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/guitarix.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/whatsdesk.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ramme.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gitter.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/franz.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/hp-printing.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ghetto_skype.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/indicator-weather.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ibus-mozc.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/overgrive.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/minetime.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/caprine.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/whatsie.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/1password.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/webtorrent-desktop.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/element.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/nutstore.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gmail-desktop.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gdlauncher.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/discord.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gajim.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/motrix.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/whatsapp-nativefier.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/wechat.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/opensnitch.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/liferea.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pushbullet-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/skype.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/solaar.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/sendanywhere.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/qtwaw.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/laditools.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/wire.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/catch-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/dropbox.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/whatsapp.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/tartube.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/listen-moe.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/twitch-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/anatine.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/protonmail.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/ytmdesktop.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/teams.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/android-messages-desktop.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/x-tile.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mattermost.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/kaku.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/nomachine.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/jdownloader.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/youtube-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/vivaldi.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/radiotray.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/irccloud.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/qjoypad.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/keepass.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/keybase.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/youtube-music.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/messenger.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rememberthemilk.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/messengerfordesktop.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/chromium.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/pomodoro-indicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/acestream.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/tusk.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/deltachat.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gitify.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/gpmdp.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/grive-tools.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/slack.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/yum-extender-dnf.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/joplin.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/vorta.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/keepassx.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/record-desktop.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/primeindicator.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/odrive.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/caprine.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/mullvad.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/electron-mail.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/signal.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/megasync.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/rocketchat.electron.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/brave.json to /usr/share/hardcode-tray/database
Installing /home/$USER/src/Hardcode-Tray/data/database/bitwarden.electron.json to /usr/share/hardcode-tray/database
Installing subdir /home/$USER/src/Hardcode-Tray/HardcodeTray to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/enum.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/tools.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/app.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/path.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/decorators.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/utils.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/parser.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/icon.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/backup.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/log.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/path.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/theme.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/svg.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/cairosvg.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/inkscape.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/svgexport.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/imagemagick.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/svg/rsvgconvert.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/svg
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/application.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/pak.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/b64electron.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/nwjs.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/electron.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/zip.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/qt.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/helpers/extract.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications/helpers
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/helpers/data_pack.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications/helpers
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/helpers/asar.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications/helpers
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/applications/helpers/binary.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/applications/helpers
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/config/system.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/config
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/config/arguments.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/config
Installing /home/$USER/src/Hardcode-Tray/HardcodeTray/modules/config/json.py to /usr/lib/python3.9/site-packages/HardcodeTray/modules/config
Installing subdir /home/$USER/src/Hardcode-Tray/license to /usr/share/hardcode-tray/license
Installing /home/$USER/src/Hardcode-Tray/license/BSD to /usr/share/hardcode-tray/license
Installing /home/$USER/src/Hardcode-Tray/license/GPL to /usr/share/hardcode-tray/license
Installing /home/$USER/src/Hardcode-Tray/license/README.md to /usr/share/hardcode-tray/license
Installing /home/$USER/src/Hardcode-Tray/data/man/hardcode-tray.1 to /usr/share/man/man1
Installing /home/$USER/src/Hardcode-Tray/builddir/const.py to /usr/lib/python3.9/site-packages/HardcodeTray
Installing /home/$USER/src/Hardcode-Tray/builddir/hardcode-tray to /usr/bin
Running custom install script '/usr/local/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=hardcode-tray'
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications.
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 108, in <module>
    print(_("Conversion Tool: {}").format(App.svg()))
  File "/usr/lib/python3.9/site-packages/HardcodeTray/app.py", line 147, in svg
    App._svgtopng = SVG.factory(App.get("colors"), conversion_tool)
  File "/usr/lib/python3.9/site-packages/HardcodeTray/modules/svg/svg.py", line 53, in factory
    svg = load(conversion_tool)(colors)
  File "/usr/lib/python3.9/site-packages/HardcodeTray/modules/svg/rsvgconvert.py", line 33, in __init__
    if not self.is_installed():
  File "/usr/lib/python3.9/site-packages/HardcodeTray/modules/svg/svg.py", line 107, in is_installed
    return is_installed(self.cmd)
  File "/usr/lib/python3.9/site-packages/HardcodeTray/utils.py", line 188, in is_installed
    ink_flag = call(['which', binary], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'which'
```

**Comment by varlesh** [comment]
`which` command used from [debianutils](https://packages.debian.org/bookworm/amd64/debianutils/filelist) package.
On Debian it's located on `/usr/bin/which`, but on Ubuntu on `/bin/which`
Try make symlink:
`sudo ln -s /usr/bin/which /bin/which`

**Comment by varlesh** [comment]
If this not helped you can use Debian 11 repo (it's compability with Python 3.9)
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/SmartFinn:/hardcode-tray/Debian_11/ /' > /etc/apt/sources.list.d/hardcode-tray.list"
wget -qO- https://download.opensuse.org/repositories/home:SmartFinn:hardcode-tray/Debian_11/Release.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install hardcode-tray
```
Or DEB-package:
http://download.opensuse.org/repositories/home:/SmartFinn:/hardcode-tray/Debian_11/all/
